name: README to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1.1.0
        with:
          input_dir: .
          output_dir: .
          build_html: false
          table_of_contents: false
      - uses: actions/upload-artifact@v3
        with:
          name: python-engineer-roadmap-upload
          path: README.pdf
      - uses: actions/download-artifact@v3
        with:
          name: python-engineer-roadmap
          path: README.pdf

