name: README to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1.1.0
        with:
          input_dir: .
          output_dir: .
          build_html: false
          table_of_contents: false
      - uses: actions/upload-artifact@v3
        with:
          name: python-engineer-roadmap
          path: README.pdf
#       - name: Commit changes
#         uses: EndBug/add-and-commit@v9
#         with:
#           default_author: github_actions
#           add: 'README.pdf'
#           new_branch: generate-pdf
#           push: origin generate-pdf --set-upstream --force
